version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /simple-cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /simple-cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /simple-cicd/docker-registry/url

phases:
  pre_build:
    commands:
      - echo Logando no Docker Hub...
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USERNAME" --password-stdin
  build:
    commands:
      - echo Iniciando build da imagem...
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-cicd:latest" .
  post_build:
    commands:
      - echo Build da imagem concluido...
      - echo Subindo imagem para o registry...
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-cicd:latest"
      - echo Processo finalizado...
